version: '3'

services:
  app:
    build:
    #   args:
    #     user: sammy
    #     uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: stock-opname
    container_name: stock-opname
    restart: unless-stopped
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
      - ./mysql/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks: 
        - stock-networks
    depends_on:
     - db
  # MySQL
  db:
    image: mysql:latest
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: "stock_opname"
      MYSQL_USER: "stock_user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - stock-mysql:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
    networks: 
        - stock-networks

  # Nginx
  web:
    image: nginx:latest
    ports:
      - "8083:83"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks: 
        - stock-networks

networks:
    stock-networks:
        driver: bridge
volumes:
    stock-mysql:
        driver: local
